# Generated by Django 3.2.9 on 2021-11-30 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='default', max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('n', 'nice'), ('b', 'bad')], default='n', max_length=1)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='photosii.tag')),
            ],
        ),
    ]
