# Generated by Django 3.2 on 2021-12-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photosii', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photos',
            field=models.ManyToManyField(blank=True, null=True, to='photosii.Photo'),
        ),
    ]
