# Generated by Django 3.2.9 on 2021-12-04 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photosii', '0002_photo_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='status',
            field=models.CharField(choices=[('n', 'Подходящая'), ('b', 'Не подходящая')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='photo',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='photosii.tag'),
        ),
    ]
