# Generated by Django 3.2 on 2021-12-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photosii', '0002_alter_customuser_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photos',
            field=models.ManyToManyField(blank=True, to='photosii.Photo'),
        ),
    ]
