# Generated by Django 3.2 on 2021-12-23 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photosii', '0003_alter_customuser_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='photos',
        ),
        migrations.AddField(
            model_name='photo',
            name='user',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='photosii.customuser'),
            preserve_default=False,
        ),
    ]
