# Generated by Django 3.2.9 on 2021-12-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photosii', '0004_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
