# Generated by Django 3.2 on 2022-02-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photosii', '0006_alter_photo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_ai_tag',
            field=models.BooleanField(default=False),
        ),
    ]
